GET https://{{host}}/api/userInfo
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJ1c2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvc3VybmFtZSI6InVzZXIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlciIsIm5iZiI6MTY1MjQ4MzM1MywiZXhwIjoxNjUyNDg2OTUzLCJpc3MiOiJrZGNsbGMiLCJhdWQiOiJhcGlzIn0.qc-0DK9LsSxSUnFX0wKcq3AJCoMIqUwFT9Jg103x4vI
